// Dados de Portugal por distrito
export const portugalDistricts = {
  "Aveiro": {
    concelhos: {
      "Águeda": ["Águeda", "Barrô", "Belazaima do Chão", "Borralha", "Castanheira do Vouga", "Espinhel", "Fermentelos", "Lamas do Vouga", "Macinhata do Vouga", "Préstimo", "Recardães", "Travassô", "Trofa", "Valongo do Vouga"],
      "Albergaria-a-Velha": ["Albergaria-a-Velha", "Angeja", "Branca", "Ribeira de Fráguas", "São João de Loure", "Valmaior"],
      "Anadia": ["Anadia", "Avelãs de Caminho", "Avelãs de Cima", "Moita", "Óis da Ribeira", "Paredes do Bairro", "Sangalhos", "São Lourenço do Bairro", "Tamengos", "Vilarinho do Bairro"],
      "Arouca": ["Alvarenga", "Arouca", "Burgo", "Canelas", "Chave", "Covelo de Paivó", "Escariz", "Espiunca", "Fermedo", "Janarde", "Mansores", "Moldes", "Rossas", "Santa Eulália", "São Miguel do Mato", "Tropeço", "Urrô", "Várzea"],
      "Aveiro": ["Aradas", "Cacia", "Eixo e Eirol", "Esgueira", "Glória e Vera Cruz", "Nariz", "Oliveirinha", "Requeixo, Nossa Senhora de Fátima e Nariz", "São Bernardo", "São Jacinto"],
      "Castelo de Paiva": ["Bairros", "Castelo de Paiva", "Fornos", "Paraíso", "Pedorido", "Raiva, Pedorido e Paraíso", "Real", "Santa Maria de Sardoura", "São Martinho de Sardoura", "Sobrado"],
      "Espinho": ["Anta e Guetim", "Espinho", "Paramos", "Silvalde"]
    }
  },
  "Beja": {
    concelhos: ["Aljustrel", "Almodôvar", "Alvito", "Barrancos", "Beja", "Castro Verde", "Cuba", "Ferreira do Alentejo", "Mértola", "Moura", "Odemira", "Ourique", "Serpa", "Vidigueira"]
  },
  "Braga": {
    concelhos: ["Amares", "Barcelos", "Braga", "Cabeceiras de Basto", "Celorico de Basto", "Esposende", "Fafe", "Guimarães", "Póvoa de Lanhoso", "Terras de Bouro", "Vieira do Minho", "Vila Nova de Famalicão", "Vila Verde", "Vizela"]
  },
  "Bragança": {
    concelhos: ["Alfândega da Fé", "Bragança", "Carrazeda de Ansiães", "Freixo de Espada à Cinta", "Macedo de Cavaleiros", "Miranda do Douro", "Mirandela", "Mogadouro", "Torre de Moncorvo", "Vila Flor", "Vimioso", "Vinhais"]
  },
  "Castelo Branco": {
    concelhos: ["Belmonte", "Castelo Branco", "Covilhã", "Fundão", "Idanha-a-Nova", "Oleiros", "Penamacor", "Proença-a-Nova", "Sertã", "Vila de Rei", "Vila Velha de Ródão"]
  },
  "Coimbra": {
    concelhos: ["Arganil", "Cantanhede", "Coimbra", "Condeixa-a-Nova", "Figueira da Foz", "Góis", "Lousã", "Mealhada", "Mira", "Miranda do Corvo", "Montemor-o-Velho", "Oliveira do Hospital", "Pampilhosa da Serra", "Penacova", "Penela", "Soure", "Tábua", "Vila Nova de Poiares"]
  },
  "Évora": {
    concelhos: ["Alandroal", "Arraiolos", "Borba", "Estremoz", "Évora", "Montemor-o-Novo", "Mora", "Mourão", "Portel", "Redondo", "Reguengos de Monsaraz", "Vendas Novas", "Viana do Alentejo", "Vila Viçosa"]
  },
  "Faro": {
    concelhos: ["Albufeira", "Alcoutim", "Aljezur", "Castro Marim", "Faro", "Lagoa", "Lagos", "Loulé", "Monchique", "Olhão", "Portimão", "São Brás de Alportel", "Silves", "Tavira", "Vila do Bispo", "Vila Real de Santo António"]
  },
  "Guarda": {
    concelhos: ["Aguiar da Beira", "Almeida", "Celorico da Beira", "Figueira de Castelo Rodrigo", "Fornos de Algodres", "Gouveia", "Guarda", "Manteigas", "Meda", "Pinhel", "Sabugal", "Seia", "Trancoso", "Vila Nova de Foz Côa"]
  },
  "Leiria": {
    concelhos: ["Alcobaça", "Alvaiázere", "Ansião", "Batalha", "Bombarral", "Caldas da Rainha", "Castanheira de Pera", "Figueiró dos Vinhos", "Leiria", "Marinha Grande", "Nazaré", "Óbidos", "Pedrógão Grande", "Peniche", "Pombal", "Porto de Mós"]
  },
  "Lisboa": {
    concelhos: ["Alenquer", "Arruda dos Vinhos", "Azambuja", "Cadaval", "Cascais", "Lisboa", "Loures", "Lourinhã", "Mafra", "Odivelas", "Oeiras", "Sintra", "Sobral de Monte Agraço", "Torres Vedras", "Vila Franca de Xira"]
  },
  "Portalegre": {
    concelhos: ["Alter do Chão", "Arronches", "Avis", "Campo Maior", "Castelo de Vide", "Crato", "Elvas", "Fronteira", "Gavião", "Marvão", "Monforte", "Nisa", "Ponte de Sor", "Portalegre", "Sousel"]
  },
  "Porto": {
    concelhos: ["Amarante", "Baião", "Felgueiras", "Gondomar", "Lousada", "Maia", "Marco de Canaveses", "Matosinhos", "Paços de Ferreira", "Paredes", "Penafiel", "Porto", "Póvoa de Varzim", "Santo Tirso", "Trofa", "Valongo", "Vila do Conde", "Vila Nova de Gaia"]
  },
  "Santarém": {
    concelhos: ["Abrantes", "Alcanena", "Almeirim", "Alpiarça", "Benavente", "Cartaxo", "Chamusca", "Constância", "Coruche", "Entroncamento", "Ferreira do Zêzere", "Golegã", "Mação", "Ourém", "Rio Maior", "Salvaterra de Magos", "Santarém", "Sardoal", "Tomar", "Torres Novas", "Vila Nova da Barquinha"]
  },
  "Setúbal": {
    concelhos: ["Alcácer do Sal", "Alcochete", "Almada", "Barreiro", "Grândola", "Moita", "Montijo", "Palmela", "Santiago do Cacém", "Seixal", "Sesimbra", "Setúbal", "Sines"]
  },
  "Viana do Castelo": {
    concelhos: ["Arcos de Valdevez", "Caminha", "Melgaço", "Monção", "Paredes de Coura", "Ponte da Barca", "Ponte de Lima", "Valença", "Viana do Castelo", "Vila Nova de Cerveira"]
  },
  "Vila Real": {
    concelhos: ["Alijó", "Boticas", "Chaves", "Mesão Frio", "Mondim de Basto", "Montalegre", "Murça", "Peso da Régua", "Ribeira de Pena", "Sabrosa", "Santa Marta de Penaguião", "Valpaços", "Vila Pouca de Aguiar", "Vila Real"]
  },
  "Viseu": {
    concelhos: ["Armamar", "Carregal do Sal", "Castro Daire", "Cinfães", "Lamego", "Mangualde", "Moimenta da Beira", "Mortágua", "Nelas", "Oliveira de Frades", "Penalva do Castelo", "Penedono", "Resende", "Santa Comba Dão", "São João da Pesqueira", "São Pedro do Sul", "Sátão", "Sernancelhe", "Tabuaço", "Tarouca", "Tondela", "Vila Nova de Paiva", "Viseu", "Vouzela"]
  }
}

export const braiderSpecialties = [
  "Tranças Nagô",
  "Tranças Boxeadoras", 
  "Tranças Soltas",
  "Twist",
  "Dreadlocks",
  "Crochet Braids",
  "Faux Locs",
  "Passion Twists",
  "Knotless Braids",
  "Fulani Braids",
  "Ghana Braids",
  "Senegalese Twists",
  "Marley Twists",
  "Havana Twists",
  "Goddess Locs",
  "Sister Locs",
  "Micro Locs",
  "Bantu Knots",
  "Cornrows",
  "French Braids",
  "Dutch Braids",
  "Fishtail Braids",
  "Waterfall Braids", 
  "Crown Braids",
  "Halo Braids",
  "Feed-in Braids",
  "Stitch Braids",
  "Lemonade Braids",
  "Tribal Braids",
  "Bohemian Braids",
  "Butterfly Locs",
  "Spring Twists",
  "Flat Twists",
  "Two Strand Twists",
  "Three Strand Twists",
  "Rope Twists",
  "Invisible Braids",
  "Tree Braids",
  "Micro Braids",
  "Jumbo Braids", 
  "Medium Braids",
  "Poetic Justice Braids",
  "Bob Braids",
  "Asymmetrical Braids",
  "Ombre Braids",
  "Colorful Braids",
  "Natural Hair Styling",
  "Protective Styling",
  "Hair Extensions",
  "Weaving",
  "Closure Installation",
  "Frontal Installation",
  "Wig Making",
  "Wig Styling",
  "Hair Washing",
  "Deep Conditioning",
  "Hot Oil Treatments",
  "Scalp Treatments",
  "Hair Cutting",
  "Hair Trimming",
  "Edge Control",
  "Silk Press",
  "Blow Drying",
  "Roller Setting",
  "Pin Curls",
  "Finger Waves",
  "Updos",
  "Special Event Styling",
  "Bridal Hair",
  "Fotoshoot Styling",
  "Editorial Hair",
  "Hair Consultations",
  "Hair Care Education",
  "Product Recommendations",
  "Scalp Massage",
  "Relaxer Application",
  "Texturizer Application", 
  "Keratin Treatments",
  "Color Services",
  "Highlights",
  "Lowlights",
  "Balayage",
  "Hair Painting",
  "Root Touch-ups",
  "Color Corrections",
  "Bleaching",
  "Toning",
  "Henna Applications",
  "Natural Hair Coloring",
  "Temporary Color",
  "Semi-Permanent Color",
  "Permanent Color",
  "Hair Glossing",
  "Hair Glazing",
  "Split End Treatments",
  "Hair Strengthening",
  "Protein Treatments",
  "Moisture Treatments",
  "Leave-in Treatments",
  "Hair Masks",
  "Scalp Detox",
  "Hair Growth Treatments",
  "Thinning Hair Solutions",
  "Alopecia Care",
  "Postpartum Hair Care",
  "Chemical Damage Repair",
  "Heat Damage Repair",
  "Overprocessed Hair Repair",
  "Hair Restoration",
  "Hair Analysis",
  "Porosity Testing",
  "Elasticity Testing",
  "Strand Testing",
  "Patch Testing",
  "Hair History Consultation",
  "Lifestyle Hair Planning",
  "Seasonal Hair Care",
  "Travel Hair Solutions",
  "Low Maintenance Styling",
  "Quick Protective Styles",
  "Wash and Go Styling",
  "Twist Outs",
  "Braid Outs",
  "Bantu Knot Outs",
  "Roller Sets",
  "Flexi Rod Sets",
  "Curlformer Sets",
  "Perm Rod Sets",
  "Straw Sets",
  "Pin Curl Sets",
  "Finger Coils",
  "Shingling Method",
  "Rake and Shake",
  "Praying Hands Method",
  "Plopping",
  "Diffusing",
  "Air Drying Techniques",
  "Protective Sleep Methods",
  "Satin/Silk Accessories",
  "Hair Wrapping Techniques",
  "Pineappling",
  "Medusa Clipping",
  "Buff Method",
  "LOC Method",
  "LCO Method",
  "Greenhouse Effect",
  "Baggy Method",
  "Inversion Method",
  "Scalp Massage Techniques",
  "Hot Towel Treatments",
  "Steam Treatments",
  "Hair Vitamins Consultation",
  "Dietary Hair Advice",
  "Stress Management for Hair",
  "Hormonal Hair Care",
  "Pregnancy Hair Care",
  "Menopause Hair Care",
  "Teen Hair Care",
  "Kids Hair Care",
  "Men's Natural Hair",
  "Beard Care",
  "Mustache Styling",
  "Eyebrow Shaping",
  "Lash Care",
  "Special Needs Hair Care",
  "Wheelchair Accessible Styling",
  "Home Visit Services",
  "Mobile Hair Services",
  "Group Styling Sessions",
  "Hair Parties",
  "Mother-Daughter Sessions",
  "Bridal Party Hair",
  "Prom Hair",
  "Graduation Hair",
  "Professional Headshots",
  "Casting Call Prep",
  "Competition Hair",
  "Dance Recital Hair",
  "Theater Hair",
  "Costume Hair",
  "Historical Hair Recreations",
  "Cultural Hair Traditions",
  "African Hair Techniques",
  "Caribbean Hair Methods",
  "Brazilian Hair Styling",
  "European Hair Techniques",
  "Asian Hair Care",
  "Mixed Heritage Hair",
  "Texture Blending",
  "Multi-Ethnic Hair",
  "Biracial Hair Care",
  "Transitioning Hair",
  "Big Chop Support",
  "Length Retention",
  "Hair Growth Tracking",
  "Progress Photos",
  "Hair Journaling",
  "Community Building",
  "Hair Mentorship",
  "Styling Workshops",
  "Hair Care Classes",
  "Product Making",
  "DIY Hair Treatments",
  "Natural Ingredient Use",
  "Organic Hair Care",
  "Chemical-Free Options",
  "Allergy-Friendly Products",
  "Sensitive Scalp Care",
  "Eczema-Safe Styling",
  "Psoriasis Hair Care",
  "Dermatitis Management",
  "Medical Hair Loss Support",
  "Cancer Patient Hair Care",
  "Alopecia Areata Styling",
  "Trichotillomania Support",
  "Hair Pulling Disorder Help",
  "Anxiety-Related Hair Issues",
  "Stress Hair Loss Solutions",
  "Postpartum Shedding Care",
  "Menopausal Hair Changes",
  "Hormonal Imbalance Hair",
  "Thyroid Hair Issues",
  "PCOS Hair Care",
  "Insulin Resistance Hair",
  "Nutritional Deficiency Hair",
  "Medication Hair Effects",
  "Seasonal Hair Changes",
  "Climate Hair Adaptation",
  "Humidity Hair Control",
  "Dry Climate Hair Care",
  "Salt Water Hair Protection",
  "Chlorine Hair Defense",
  "Sun Protection for Hair",
  "Winter Hair Care",
  "Summer Hair Maintenance",
  "Spring Hair Renewal",
  "Fall Hair Preparation",
  "Holiday Hair Styling",
  "New Year Hair Goals",
  "Valentine's Day Hair",
  "Easter Hair Styles",
  "Summer Vacation Hair",
  "Back to School Hair",
  "Halloween Hair",
  "Thanksgiving Hair",
  "Christmas Hair Styling",
  "Birthday Hair Specials",
  "Anniversary Hair",
  "Date Night Hair",
  "Girls Night Hair",
  "Work Hair Solutions",
  "Interview Hair Prep",
  "Professional Hair Styling",
  "Casual Hair Options",
  "Weekend Hair Looks",
  "Gym Hair Solutions",
  "Sports Hair Styling",
  "Athletic Hair Care",
  "Swimming Hair Protection",
  "Yoga Hair Styles",
  "Dance Hair Preparation",
  "Running Hair Solutions",
  "Cycling Hair Care",
  "Hiking Hair Prep",
  "Beach Hair Styles",
  "Pool Hair Protection",
  "Travel Hair Kits",
  "Vacation Hair Planning",
  "Destination Wedding Hair",
  "Honeymoon Hair Care",
  "Business Travel Hair",
  "Long Flight Hair Prep",
  "Hotel Hair Solutions",
  "Camping Hair Care",
  "Festival Hair Styling",
  "Concert Hair Looks",
  "Club Hair Styles",
  "Restaurant Hair Elegance",
  "Theater Hair Preparation",
  "Opera Hair Styling",
  "Gallery Opening Hair",
  "Charity Event Hair",
  "Fundraiser Hair Looks",
  "Corporate Event Hair",
  "Conference Hair Styling",
  "Seminar Hair Preparation",
  "Workshop Hair Solutions",
  "Class Hair Styles",
  "Study Group Hair",
  "Library Hair Looks",
  "Coffee Date Hair",
  "Lunch Date Hair Styling",
  "Dinner Date Hair Elegance",
  "Movie Date Hair",
  "Mini Golf Hair Fun",
  "Bowling Hair Styles",
  "Ice Skating Hair",
  "Roller Skating Hair",
  "Amusement Park Hair",
  "Zoo Visit Hair",
  "Museum Hair Styling",
  "Art Class Hair",
  "Cooking Class Hair",
  "Wine Tasting Hair",
  "Book Club Hair",
  "Garden Party Hair",
  "BBQ Hair Styles",
  "Picnic Hair Solutions",
  "Outdoor Wedding Hair",
  "Indoor Wedding Hair",
  "Church Hair Styling",
  "Temple Hair Preparation",
  "Mosque Hair Coverage",
  "Synagogue Hair Styles",
  "Religious Ceremony Hair",
  "Cultural Event Hair",
  "Traditional Celebration Hair",
  "Modern Event Hair",
  "Fusion Style Hair",
  "Contemporary Hair Looks",
  "Classic Hair Styling",
  "Vintage Hair Recreation",
  "Retro Hair Styles",
  "1920s Hair Looks",
  "1930s Hair Styling",
  "1940s Hair Victory Rolls",
  "1950s Hair Bouffant",
  "1960s Hair Beehives",
  "1970s Hair Feathers",
  "1980s Hair Volume",
  "1990s Hair Straightness",
  "2000s Hair Layers",
  "2010s Hair Waves",
  "2020s Hair Textures",
  "Future Hair Trends",
  "Sustainable Hair Care",
  "Eco-Friendly Styling",
  "Zero Waste Hair",
  "Minimal Hair Products",
  "DIY Hair Solutions",
  "Budget Hair Care",
  "Affordable Styling",
  "High-End Hair Services",
  "Luxury Hair Treatments",
  "Spa Hair Experience",
  "Relaxation Hair Services",
  "Meditation Hair Time",
  "Mindful Hair Care",
  "Spiritual Hair Rituals",
  "Ceremonial Hair Prep",
  "Blessing Hair Styles",
  "Prayer Hair Coverage",
  "Meditation Hair Prep",
  "Yoga Hair Solutions",
  "Chakra Hair Alignment",
  "Energy Hair Healing",
  "Crystal Hair Therapy",
  "Aromatherapy Hair Care",
  "Essential Oil Hair Treatments",
  "Herbal Hair Remedies",
  "Ayurvedic Hair Care",
  "Traditional Chinese Hair Medicine",
  "Holistic Hair Approach",
  "Natural Hair Philosophy",
  "Organic Hair Lifestyle",
  "Clean Hair Products",
  "Non-Toxic Hair Care",
  "Safe Hair Practices",
  "Gentle Hair Methods",
  "Caring Hair Approach",
  "Loving Hair Touch",
  "Nurturing Hair Environment",
  "Supportive Hair Community",
  "Inclusive Hair Services",
  "Diverse Hair Celebration",
  "Cultural Hair Appreciation",
  "Heritage Hair Honoring",
  "Ancestral Hair Techniques",
  "Family Hair Traditions",
  "Generational Hair Wisdom",
  "Elder Hair Respect",
  "Youth Hair Empowerment",
  "Teen Hair Confidence",
  "Adult Hair Sophistication",
  "Senior Hair Grace",
  "Life Stage Hair Adaptation",
  "Milestone Hair Celebration",
  "Achievement Hair Styling",
  "Success Hair Looks",
  "Confidence Hair Boost",
  "Self-Love Hair Care",
  "Self-Care Hair Time",
  "Mental Health Hair Support",
  "Emotional Hair Healing",
  "Therapeutic Hair Touch",
  "Healing Hair Environment",
  "Recovery Hair Care",
  "Wellness Hair Journey",
  "Health Hair Focus",
  "Vitality Hair Enhancement",
  "Energy Hair Boost",
  "Strength Hair Building",
  "Resilience Hair Development",
  "Growth Hair Mindset",
  "Progress Hair Tracking",
  "Goals Hair Achievement",
  "Dreams Hair Manifestation",
  "Vision Hair Realization",
  "Purpose Hair Alignment",
  "Mission Hair Support",
  "Values Hair Expression",
  "Beliefs Hair Reflection",
  "Identity Hair Affirmation",
  "Authenticity Hair Embrace",
  "Uniqueness Hair Celebration",
  "Individuality Hair Honor",
  "Personality Hair Expression",
  "Character Hair Reflection",
  "Soul Hair Connection",
  "Spirit Hair Alignment",
  "Heart Hair Opening",
  "Mind Hair Clearing",
  "Body Hair Nourishing",
  "Whole Hair Being",
  "Complete Hair Wellness",
  "Total Hair Transformation",
  "Ultimate Hair Experience",
  "Perfect Hair Moment",
  "Beautiful Hair Journey",
  "Wonderful Hair Adventure",
  "Amazing Hair Discovery",
  "Incredible Hair Evolution",
  "Fantastic Hair Transformation",
  "Outstanding Hair Results",
  "Exceptional Hair Service",
  "Superior Hair Quality",
  "Premium Hair Experience",
  "Elite Hair Treatment",
  "Exclusive Hair Access",
  "Special Hair Attention",
  "Personal Hair Focus",
  "Individual Hair Care",
  "Custom Hair Solutions",
  "Tailored Hair Approach",
  "Personalized Hair Service",
  "Specialized Hair Expertise",
  "Professional Hair Knowledge",
  "Expert Hair Skills",
  "Master Hair Techniques",
  "Advanced Hair Methods",
  "Cutting-Edge Hair Technology",
  "Innovative Hair Solutions",
  "Creative Hair Artistry",
  "Artistic Hair Expression",
  "Beautiful Hair Creation",
  "Stunning Hair Results",
  "Gorgeous Hair Outcomes",
  "Lovely Hair Transformations",
  "Elegant Hair Styles",
  "Sophisticated Hair Looks",
  "Refined Hair Techniques",
  "Polished Hair Results",
  "Flawless Hair Execution",
  "Perfect Hair Precision",
  "Exact Hair Methods",
  "Precise Hair Application",
  "Accurate Hair Assessment",
  "Detailed Hair Analysis",
  "Thorough Hair Examination",
  "Complete Hair Evaluation",
  "Comprehensive Hair Review",
  "Full Hair Understanding",
  "Deep Hair Knowledge",
  "Extensive Hair Experience",
  "Broad Hair Expertise",
  "Wide Hair Skills",
  "Vast Hair Understanding",
  "Infinite Hair Possibilities",
  "Endless Hair Options",
  "Unlimited Hair Potential",
  "Boundless Hair Creativity",
  "Limitless Hair Innovation",
  "Eternal Hair Beauty",
  "Timeless Hair Elegance",
  "Classic Hair Grace",
  "Traditional Hair Wisdom",
  "Modern Hair Solutions",
  "Contemporary Hair Approaches",
  "Current Hair Trends",
  "Latest Hair Techniques",
  "Newest Hair Methods",
  "Fresh Hair Ideas",
  "Original Hair Concepts",
  "Unique Hair Perspectives",
  "Different Hair Approaches",
  "Alternative Hair Solutions",
  "Varied Hair Options",
  "Diverse Hair Choices",
  "Multiple Hair Possibilities",
  "Many Hair Opportunities",
  "Numerous Hair Benefits",
  "Countless Hair Advantages",
  "Infinite Hair Rewards",
  "Endless Hair Satisfaction",
  "Unlimited Hair Joy",
  "Boundless Hair Happiness",
  "Limitless Hair Confidence",
  "Eternal Hair Self-Love",
  "Timeless Hair Beauty",
  "Forever Hair Elegance"
]